name = "EventEmitter"
uuid = "eed75e0f-2a47-456c-84f6-69ee3fe4bbf9"
authors = ["Spirit <spirit@programmer.net>"]
repo = "https://github.com/spirit-x64/EventEmitter.jl.git"
version = "1.0.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
